name: Documents

on:
  push:
    branches:
    - main
    - release-*
  pull_request:
    branches:
    - main
    - release-*

jobs:
  skip-check:
    name: Skip check
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip-check.outputs.should_skip }}
    permissions:
      actions: write
      contents: read
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@9d116fa7e55f295019cfab7e3ab72b478bcf7fdd # tag=v4.0.0
        with:
          do_not_skip: '["schedule", "workflow_dispatch"]'
          paths: |-
            [
              ".github/workflows/docs.yml",
              ".go-version",
              "Makefile",
              "main.go",
              "docs"
            ]
          skip_after_successful_duplicate: false

  docs:
    name: Generate documentation
    needs: skip-check
    if: ${{ needs.skip-check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Set up Go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # tag=v3.2.1
        with:
          go-version-file: .go-version
          cache: true

      - name: Install LLVM (BPF dependency)
        run: |
          sudo apt-get update -y
          sudo apt-get install -yq llvm-dev libclang-dev

      - name: Install libbpf dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -yq libelf-dev zlib1g-dev

      - name: Initialize and update libbpf submodule
        run: git submodule init && git submodule update

      - name: Build libbpf
        run: make libbpf

      - name: Build BPF
        run: make bpf

      - name: Build
        run: make build

      - name: Set up tools
        run: ./env.sh

      - name: Docs check
        run: |
          make README.md
          git diff --exit-code
